### ISSUE TITLE
Improve operational right navigation

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-statemod-fortran-doc-user#7]
The operational rights documentation could be improved as follows:

1. Split the examples up onto multiple code blocks so that horizontal scrolling is accessible for each example.  Also add title to the example.
2. For the table that lists rights, make the section references links.

Note that MkDocs will indicate bad links in the shell window so it is usually easy to fix broken links that sneak in.

**Comment by macphersonbr** [comment]
Accomplished task 2, referencing links in 413.md. Decided not to do task 1 (in 41351.md) because the text is meant to be an example .opr file that can be copy/pasted into the user's directory. Splitting the text into separate sections would break that.
