### ISSUE TITLE
Improve command line documentation

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-statemod-fortran-doc-user#8]
The following page could be improved:

[Model Operation](http://opencdss.state.co.us/statemod/latest/doc-user/Model%20Operation/6/)

as follows:

1. The report command line examples need to be formatted as constant width font.
2. Providing an actual example with a response file name (e.g., `cm2015.rsp`) would be helpful.
3. You have to be careful using underscores because they have meaning in Markdown.  The footnote at the bottom mentions a parameter that has an underscore in it.  I recommend surrounding all filenames and input with ticks to make the text stand out from other text and to avoid underscore issue.
4. The order of the filename and options is important (the code could be enhanced so that this is not the case).
5. The UNIX bug that is mentioned needs to be fixed.

**Comment by macphersonbr** [comment]
Hey Steve,
I'm confused about a few of these. 

1. See updated version. Is that what you mean?

2. OK. See update. In my testing using a file name of either cm2015 or cm2015.rsp works. 

3. I don't see any underscores. Do you think that  "River Outflow" is supposed to have an underscore? 

4. Noted. See update. 

5. Noted.

**Comment by smalers** [comment]
Yes, the StateMod binary file uses parameters that have underscores.  Ideally, this documentation should include or link to a table that lists those parameters with a description of the parameter.  TSTool's `ReadStateModB` command can be used to read all time series for one location to show the parameter names.  Explaining those parameters in a way that an average person can understand would be a big help.  The other changes look good.

**Comment by macphersonbr** [comment]
Closing issue #8.
